var website_url = 
{
	"党委办公室、校长办公室" : "http://office.scnu.edu.cn",
	"组织部" : "http://hsdj.scnu.edu.cn",
	"纪委监察处" : "http://jwjc.scnu.edu.cn",
	"人事处" : "http://rsc.scnu.edu.cn",
	"学生工作部（处）、人民武装部" : "http://xsb.scnu.edu.cn",
	"教务处" : "http://jw.scnu.edu.cn",
	"国际交流合作处" : "http://io.scnu.edu.cn",
	"基建处" : "http://jjc.scnu.edu.cn",
	"保卫处" : "http://bwc.scnu.edu.cn",
	"科技处" : "http://kjc.scnu.edu.cn/business/website/mainPageIndex.do",
	"招生考试处" : "http://zkc.scnu.edu.cn",
	"省高校师资培训中心" : "http://gdsz.scnu.edu.cn",
	"研究生院（处）" : "http://yjsy.scnu.edu.cn",
	"社科处" : "http://skc.scnu.edu.cn",
	"财务处" : "http://hscw.scnu.edu.cn",
	"资产管理处" : "http://amd.scnu.edu.cn",
	"后勤管理处" : "http://szhq.scnu.edu.cn/dsh",
	"校团委" : "http://zijingwang.org/xtw",
	"校工会" : "http://gh.scnu.edu.cn/aprescms",
	"发展规划处" : "http://fzghb.scnu.edu.cn",
	"社会服务处" : "http://shfw.scnu.edu.cn",
	"离退休工作办公室" : "http://ltb.scnu.edu.cn",
	"审计处" : "http://portal.scnu.edu.cn/wps/portal/sjc",
	"机关党委" : "http://jgdw.scnu.edu.cn",

	"文学院" : "http://wxy.scnu.edu.cn",
	"历史文化学院" : "http://lswh.scnu.edu.cn",
	"法学院" : "http://fxy.scnu.edu.cn",
	"政治与行政学院" : "http://zhx.scnu.edu.cn",
	"马克思主义学院" : "http://mks.scnu.edu.cn",
	"经济与管理学院" : "http://em.scnu.edu.cn",
	"教育科学学院" : "http://jky.scnu.edu.cn",
	"心理学院" : "http://psy.scnu.edu.cn",
	"外国语言文化学院" : "http://sfs.scnu.edu.cn",
	"公共管理学院" : "http://ggy.scnu.edu.cn",
	"体育科学学院" : "http://sport.scnu.edu.cn",
	"生命科学学院" : "http://life.scnu.edu.cn",
	"教育信息技术学院" : "http://site.scnu.edu.cn",
	"信息光电子科技学院" : "http://ioe.scnu.edu.cn",
	"网络教育学院" : "http://www.gdou.com",
	"继续教育学院" : "http://cce.scnu.edu.cn",
	"物理与电信工程学院" : "http://physics.scnu.edu.cn",
	"数学科学学院" : "http://maths.scnu.edu.cn",
	"化学与环境学院" : "http://sce.scnu.edu.cn",
	"计算机学院" : "http://cs.scnu.edu.cn",
	"地理科学学院" : "http://geography.scnu.edu.cn",
	"音乐学院" : "http://music.scnu.edu.cn",
	"美术学院" : "http://aol.scnu.edu.cn",
	"基础教育培训与研究院" : "http://jjy.scnu.edu.cn",
	"旅游管理学院" : "http://stm.scnu.edu.cn",
	"国际文化学院" : "http://cicgz.scnu.edu.cn",
	"国际商学院" : "http://ibc.scnu.edu.cn",
	"软件学院" : "http://ss.scnu.edu.cn",
	"城市文化学院" : "http://cswh.scnu.edu.cn",
	"凤凰国际学院" : "http://phoenix.scnu.edu.cn",
	"职业教育学院" : "http://zyjy.scnu.edu.cn",
	"创业学院" : "http://es.scnu.edu.cn",
	"脑科学与康复医学研究院" : "http://ibrr.scnu.edu.cn",


	"图书馆" : "http://lib.scnu.edu.cn",
	"教务管理系统" : "http://jwc.scnu.edu.cn",
};


var website_english =
{
	"党委办公室、校长办公室" : "President's Office of SCNU",
	"组织部" : "Organization Department,SCNU",
	"纪委监察处" : "Commission for Discipline Inspection,SCNU",
	"人事处" : "Human Resources Department,SCNU",
	"学生工作部（处）、人民武装部" : "Student Affairs Department, people's armed forces department,SCNU",
	"教务处" : "Dean's Office,SCNU",
	"国际交流合作处" : "Office Of International Exchange and Cooperation,SCNU",
	"基建处" : "Capital Construction Department,SCNU",
	"保卫处" : "BWC,SCNU",
	"科技处" : "Technology Department,SCNU",
	"招生考试处" : "Entrance Examination Committee Office",
	"省高校师资培训中心" : "Guangdong Teachers Training Center For Institutions of Higher Learning",
	"研究生院（处）" : "Graduate School,SCNU",
	"社科处" : "Office of Humanities and Social Sciences Division,SCNU",
	"财务处" : "Finance Department,SCNU",
	"资产管理处" : "Asset Management Office,SCNU",
	"后勤管理处" : "Logistics Management Office,SCNU",
	"校团委" : "Youth League,SCNU",
	"校工会" : "Trade Union,SCNU",
	"发展规划处" : "Development and Planning Department,SCNU",
	"社会服务处" : "Social Service,SCNU",
	"离退休工作办公室" : "Retired Work Office,SCNU",
	"审计处" : "Audit Office,SCNU",
	"机关党委" : "Party Committee,SCNU",

	"文学院" : "School of Literature",
	"历史文化学院" : "School of History and Culture",
	"法学院" : "School of Law",
	"政治与行政学院" : "School of Politics and Administration",
	"马克思主义学院" : "School of Marxism",
	"经济与管理学院" : "School of Economics and Management",
	"教育科学学院" : "School of Education",
	"心理学院" : "School of Psychology",
	"外国语言文化学院" : "School of Foreign Studies",
	"公共管理学院" : "School of Public Administration",
	"体育科学学院" : "School of Physical Education and Sports Science",
	"生命科学学院" : "School of Life Sciences",
	"教育信息技术学院" : "School of Information Technology in Education",
	"信息光电子科技学院" : "School of Information and Optoelectronic Science and Engineering",
	"网络教育学院" : "School of Network Education",
	"继续教育学院" : "College of Continuing Education",
	"物理与电信工程学院" : "School of Physics and Telecommunications Engineering",
	"数学科学学院" : "School of Mathematical Sciences",
	"化学与环境学院" : "School of Chemistry and Environment",
	"计算机学院" : "School of Computer Science",
	"地理科学学院" : "School of Geography",
	"音乐学院" : "School of Music",
	"美术学院" : "School of Fine Arts",
	"基础教育培训与研究院" : "School of Professional Development and Research on Primary and Secondary Education",
	"旅游管理学院" : "School of Tourism Management",
	"国际文化学院" : "College of International Culture",
	"国际商学院" : "International Business College",
	"软件学院" : "School of Software",
	"城市文化学院" : "School of Urban Culture",
	"凤凰国际学院" : "Phoenix International College",
	"职业教育学院" : "Vocational Education College",
	"创业学院" : "School of Entrepreneurship",
	"脑科学与康复医学研究院" : "Institute for Brain Research and Rehabilitation",


	"图书馆" : "lib",
	"教务管理系统" : "jwc",
}